// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAx9Xe365Az1D8o5UpsIip2W1iqFBV79A',
    appId: '1:695765900478:web:9ceec5acb402efdce952ef',
    messagingSenderId: '695765900478',
    projectId: 'just-161d4',
    authDomain: 'just-161d4.firebaseapp.com',
    storageBucket: 'just-161d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMWK86SyFUxPNGYw2WZC8058zBKgVFtFg',
    appId: '1:695765900478:android:d228d8bb60bb142ae952ef',
    messagingSenderId: '695765900478',
    projectId: 'just-161d4',
    storageBucket: 'just-161d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxNHBuBl7HSADdjwoIPXxCTHs6qYXz8M',
    appId: '1:695765900478:ios:e6c494da816ae9fbe952ef',
    messagingSenderId: '695765900478',
    projectId: 'just-161d4',
    storageBucket: 'just-161d4.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxNHBuBl7HSADdjwoIPXxCTHs6qYXz8M',
    appId: '1:695765900478:ios:e6c494da816ae9fbe952ef',
    messagingSenderId: '695765900478',
    projectId: 'just-161d4',
    storageBucket: 'just-161d4.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAx9Xe365Az1D8o5UpsIip2W1iqFBV79A',
    appId: '1:695765900478:web:a11c68445cd69684e952ef',
    messagingSenderId: '695765900478',
    projectId: 'just-161d4',
    authDomain: 'just-161d4.firebaseapp.com',
    storageBucket: 'just-161d4.firebasestorage.app',
  );
}
